<a href="https://colab.research.google.com/github/chaityrahman154-lgtm/The-beginning-is-today/blob/main/CSE220.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
 import numpy as np

###Right shift, left shift, rotate shift, k time shifting


In [ ]:
#WRONG right shifting
arr=np.array([10,20,30,40,50,60])
for i in range(1,len(arr)):
    arr[i]=arr[i-1]
arr[0]=0
print(arr)

[ 0 10 10 10 10 10]


In [ ]:
#Right shifting
arr=np.array([10,20,30,40,50,60])
for i in range(len(arr)-1,-1,-1):
    arr[i]=arr[i-1]
arr[0]=0
print(arr)

[ 0 10 20 30 40 50]


In [ ]:
#Left shifting
lst=np.array([10,20,30,40,50,60])
for i in range(len(lst)-1):
    lst[i]=lst[i+1]
lst[-1]=0
print(lst)

[20 30 40 50 60  0]


In [ ]:
#Rotate right
lst=np.array([10,20,30,40,50,60])
temp=lst[-1]
for i in range(len(lst)-1,-1,-1):
    lst[i]=lst[i-1]
lst[0]=temp
print(lst)

[60 10 20 30 40 50]


In [ ]:
#k time right shifting
arr=np.array([10,20,30,40,50,60])
k=2
for i in range(len(arr)-1,k-1,-1):
    arr[i]=arr[i-k]
for i in range(k):
    arr[i]=0
print(arr)

[ 0  0 10 20 30 40]


In [ ]:
#k time rotate shifting
arr=np.array([10,20,30,40,50,60,70])
k=4
lst=[]
idx=len(arr)-1
for i in range(k):
    lst.append(arr[idx])
    idx-=1
for i in range(len(arr)-1,k-1,-1):
    arr[i]=arr[i-k]
idx=len(lst)-1
for i in range(k):
    arr[i]=lst[idx]
    idx-=1
print(arr)

[40 50 60 70 10 20 30]


Linear array to Circular array, print all element of an array, print it reversely, insert new element in empty spot, Resize, Remove
---

**[0 0 10 20 30 40 0] -> size = 4, length = 7, starting index=2, last element=(starting_index+(arr.size-1))%len(arr)**

In [ ]:
#Creating a circular array
arr=np.array([10,20,30,40,50,60,0]) #[50 60 10 20 30 40]
circular_arr=np.array([0]*len(arr))
starting_i=2  #the number of the index at which the circular array will be started
size=arr.size
print(size)
for i in range(size):
    circular_arr[starting_i]=arr[i]
    starting_i=(starting_i+1)%len(arr) # so that when i will be equal to lenght it will again start iterating from index 0
print(circular_arr)

7
[60  0 10 20 30 40 50]


In [ ]:
a=np.array([0,0,10,20,30,40,0])  # but I heard size is 4???
print(a.size)

7


In [ ]:
#print all the element
starting_i=2
for i in range(circular_arr.size):
    print(circular_arr[starting_i])
    starting_i=(starting_i+1)%len(arr)


10
20
30
40
50
60
0


In [ ]:
#print reversely [50 60 10 20 30 40]
starting_i=2
for i in range(circular_arr.size):
    starting_i=(circular_arr.size+starting_i-1)%len(arr)
    print(circular_arr[starting_i])

0
60
50
40
30
20
10


In [ ]:
#insert new element
arr=np.array([60,0,10,20,30,40,50])
new_element=70
last_element_idx=(circular_arr.size+starting_i-1)%len(arr)
if arr[last_element_idx+1]==0:
    arr[last_element_idx+1]=new_element
print(arr)

[60  0 10 20 30 40 50]


In [ ]:
arr=np.array([10,20,30,0,0])  #linear array not circular
idx=1          #  4            1    -1 = 4 3 2
for i in range(len(arr)-1,idx,-1):  # right shifting
    arr[i]=arr[i-1]
arr[idx]=15
print(arr)

[10 15 20 30  0]


In [ ]:
#You have to insert the elem in idx index. However, if there's no space left in the array.
#You must copy the array into a double sized array and then insert the element.
def insert(arr,idx,elem):
    no_space=None
    for i in range(len(arr)):
        if arr[i]==0:
            no_space=False
            break
        else:
            no_space=True
    if no_space:
        new_arr=np.zeros(len(arr)*2,dtype=int)
        for i in range(len(arr)):
            new_arr[i]=arr[i]
        arr=new_arr
    for i in range(len(arr)-1,idx,-1):
        arr[i]=arr[i-1]
    arr[idx]=elem
    print(arr)

arr = np.array([11,22,33,44,55])
insert(arr,2,100)

arr = np.array([11,22,33,44,55,0])
insert(arr,2,100)

[ 11  22 100  33  44  55   0   0   0   0]
[ 11  22 100  33  44  55]


In [ ]:
#Resize
arr=np.array([60,70,10,20,30,40,50])
size=9
starting_i=2
starting_j=2
new_arr=np.array([0]*size)
for i in range(arr.size):
    new_arr[starting_i]=arr[starting_j]
    starting_j=(starting_j+1)%len(arr)    # 10-50 hoar por abar 0 number index
    starting_i=(starting_i+1)%len(new_arr) # 10-70 abr 0 number index
print(new_arr)

[ 0  0 10 20 30 40 50 60 70]


In [ ]:
1#Remove
arr=np.array([60,70,10,20,30,40,50])
element=70
for i in range(len(arr)):
    if arr[i]==element:
        arr[i]=0
print(arr)

[60  0 10 20 30 40 50]


In [ ]:
arr=np.array([10,20,30,40,50])
n=2
for i in range(n,len(arr)-1):
    arr[i]=arr[i+1]
arr[len(arr)-1]=0
print(arr)

[10 20 40 50  0]


In [ ]:
arr=np.array([60,70,10,20,30,40,50]) # [60 70 10 20 0 40 50]=> [60 70 0 10 20 40 50]
element_i=4
starting_i=2
last_element=(arr.size+starting_i-1)%len(arr) # 1
for i in range(element_i,last_element,-1):  # 4 3 2
    arr[i]=arr[i-1]
arr[last_element+1]=0
print(arr)

[60 70  0 10 20 40 50]


Sort
---

In [ ]:
#Bubble sort
arr=np.array([10,5,8,9,3,7])
for i in range(arr.size):
    for j in range(arr.size-1-i): # i=number of how many numbers have been sorted in each iteration
        if arr[j]>arr[j+1]:
            temp=arr[j]
            arr[j]=arr[j+1]
            arr[j+1]=temp
print(arr)

[ 3  5  7  8  9 10]


In [ ]:
#Selection sort
arr=np.array([5,10,8,9,3,7])
for i in range(arr.size):
    small_idx=i
    for j in range(i+1,arr.size):
        if arr[j]<arr[small_idx]:
            small_idx=j
    temp=arr[i]
    arr[i]=arr[small_idx]
    arr[small_idx]=temp
print(arr)

[ 3  5  7  8  9 10]


Binary Search
---

Multi Dimentional Array
---







In [ ]:
import numpy as np
arr2D = np.zeros(shape=(3,4), dtype = int)
total_cells = arr2D.size #12

In [ ]:
#Row Major Traversal
arr=np.array([[1, 2, 3],
                      [4, 5, 6],
                      [7, 8, 9]])
for r in range(arr.shape[0]):
    for c in range(arr.shape[1]):
        print(arr[r][c],end=" ")
    print()

1 2 3 
4 5 6 
7 8 9 


In [ ]:
#Column Major Traversal
arr=np.array([[1, 2, 3],
                      [4, 5, 6]])
for c in range(arr.shape[1]):
    for r in range(arr.shape[0]):
        print(arr[r][c],end=" ")
    print()

1 4 
2 5 
3 6 


In [ ]:
#Transpose
arr=np.array([[1, 2, 3],
                      [4, 5, 6]])
r_len, c_len = arr.shape
new_arr = np.zeros(shape=(c_len, r_len), dtype=int)
for i in range(c_len):
    for j in range(r_len):
        new_arr[i][j]=arr[j][i]
print(arr)
print(new_arr)

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


In [ ]:
#Swap two columns of a mX2 matrix
arr=np.array([[1,2],
                      [3,4],
                      [5,6]])
for i in range(arr.shape[0]):
    for j in range(arr.shape[1]-1):
        arr[i][j],arr[i][j+1]=arr[i][j+1],arr[i][j]
print(arr)

[[2 1]
 [4 3]
 [6 5]]


In [ ]:
#Swap two columns of mxn matrix
arr=np.array([[1, 2, 3],
                      [4, 5, 6],
                      [7, 8, 9]])
for i in range(arr.shape[0]):
    for j in range(arr.shape[1]-1):
        arr[i][j],arr[i][j+1]=arr[i][j+1],arr[i][j]
print(arr)

In [ ]:
import numpy as np
arr=np.array([[1, 2, 3,10,13,16], #5-0 = 5  5-1 =  4  5-2 = 3 arr.shape[1]-1-j=new j
                      [4, 5, 6,11,14,17],
                      [7, 8, 9,12,15,18]])
print(arr.shape[1])
for i in range(arr.shape[0]):
    for j in range(arr.shape[1]//2):
        arr[i][j],arr[i][arr.shape[1]-1-j]=arr[i][arr.shape[1]-1-j],arr[i][j]
print(arr)

6
[[16 13 10  3  2  1]
 [17 14 11  6  5  4]
 [18 15 12  9  8  7]]


In [ ]:
#Secondary Diagonal of Square Mtarix
arr=np.array([[1, 2, 3],  # 0 2
                      [4, 5, 6],  # 1 1
                      [7, 8, 9]]) # 2 0
for i in range(arr.shape[0]):
    for j in range(arr.shape[0]):
        if i == c_len-1-j:       # try to find out another technique
            print(arr[i][j],end=" ")

3 5 7 

In [ ]:
#Sum of every row
arr=np.array([[1, 2, 3],
                      [4, 5, 6],
                      [7, 8, 9]])
new_arr=np.zeros((arr.shape[0],1),dtype=int)
for i in range(arr.shape[0]):
    s=0
    for j in range(arr.shape[1]):
        s+=arr[i][j]
    new_arr[i][0]=s
print(new_arr)

[[ 6]
 [15]
 [24]]


In [ ]:
#Sum of every column
arr=np.array([[1, 2, 3],
                      [4, 5, 6],
                      [7, 8, 9]])
new_arr=np.zeros((1,arr.shape[1]),dtype=int)
for i in range(arr.shape[1]):
    s=0
    for j in range(arr.shape[0]):
        s+=arr[j][i]
    new_arr[0][i]=s
print(new_arr)

[[12 15 18]]


In [ ]:
#Add two matrixes of same dimension
arr1=np.array([[1,2,3],
                        [4,5,6]])
arr2=np.array([[7,8,9],
                       [10,11,12]])
new_arr=np.zeros((arr1.shape[0],arr1.shape[1]),dtype=int)
for i in range(arr1.shape[0]):
    for j in range(arr1.shape[1]):
        new_arr[i][j]=arr1[i][j]+arr2[i][j]
print(new_arr)

[[ 8 10 12]
 [14 16 18]]


In [ ]:
#Add elements of primary diagonal
arr1=np.array([[1,2,3],
                        [4,5,6],
                        [7,8,9]])
s=0
for i in range(arr1.shape[0]):
    for j in range(arr1.shape[1]):
        if i==j:
            s+=arr[i][j]
print(s)

15


In [ ]:
#Max value of row_wise min value

In [ ]:
# Matrix Multiplication - the number of columns in the first matrix must be equal to the number of rows in the second matrix
import numpy as np
m1 = np.array([[1,5],
               [2,6],
               [3,7],
               [4,8]])

m2 = np.array([[1,2,3],
               [4,5,6]])

m1_r, m1_c = m1.shape
m2_r, m2_c = m2.shape

m3 = np.zeros( shape=(m1_r, m2_c),dtype=int )

# rows of M1 or M3
for i in range(m1.shape[0]):
   # cols of M2 or M3
   for j in range(m2.shape[1]):
       # iterate through rows of M2
       for k in range(m1.shape[1]):
           m3[i][j] += m1[i][k] * m2[k][j]
print(m1)
print(m2)
print(m3)

[[1 5]
 [2 6]
 [3 7]
 [4 8]]
[[1 2 3]
 [4 5 6]]
[[21 27 33]
 [26 34 42]
 [31 41 51]
 [36 48 60]]


Linked List
--

In [ ]:
#Create LinkedList class
class Node:
    def __init__(self,data,address):
        self.elem=data
        self.next=address


n1=Node(10,None)
n2=Node(20,None)
n3=Node(30,None)
n1.next=n2
n2.next=n3
head=n1

In [ ]:
# print linklist
def printLL(head):
    n = head
    while n!=None:
        print(n.elem, end=' -> ')
        n = n.next

In [ ]:
#interate
class Node:
    def __init__(self,elem,next=None):
        self.elem = elem
        self.next = next
n1 = Node(10)
n2 = Node(20)
n3 = Node(30)
n4 = Node(40)
n1.next = n2
n2.next = n3
n3.next = n4
head = n1

n = head
while n!=None:
    print(n.elem, end=' -> ')
    n = n.next

10 -> 20 -> 30 -> 40 -> 

In [ ]:
#array to Linked List
class LinkedList:
    def __init__(self,arr):
        head=None
        tail=None
        for i in arr:
            n=Node(i,None)
            if head==None:
                head=n
                tail=n
            else:
                tail.next=n
                tail=n
        print(head.elem)
import numpy as np
arr=np.array([10, 20, 30, 40, 50])
a=LinkedList(arr)

10


In [ ]:
# access a node
def acc_node(head,idx):
    c=0
    n=head
    while n!=None:
        if c==idx:
            return n
        c+=1
        n=n.next

In [ ]:
def appendLL(tail,data):
    newNode = Node(data)
    tail.next = newNode
    tail = newNode
def prependLL(head,data):
    newNode = Node(data)
    newNode.next = head
    head = newNode
appendLL(n3,50)

In [ ]:
#insert a new node
def ins_node(head,idx,elem):
    new=Node(elem,None)
    if idx<0:
        return None
    elif idx==0:
        new.next=head
        head=new
        return head
    else:
        prv=acc_node(head,idx-1)
        next=prv.next
        prv.next=new
        new.next=next
        return head
x=ins_node(n1,-1,55)
if x==None:
    print("Insert failed")
else:
    head=x
printLL(x)

Insert failed


In [ ]:
#remove
def rmv_node(head,idx):
    if idx<0:
        return None
    elif idx==0:
        rmvnod=head
        head=head.next
        rmvnod.next=None
        return head
    else:
        prv=acc_node(head,idx-1)
        rmvnod=prv.next
        next=rmvnod.next
        prv.next=next
        rmvnod.next=None
        return head
x=rmv_node(n1,2)
if x==None:
    print("Remove Failed")
else:
    head=x
printLL(head)


10 -> 20 -> 

In [ ]:
#reverse
def reverseLL(head): #n1 n2 n3 n4 -> n4 n3 n2 n1
        n = head # n1
        while n != None:
            after = n.next  # n2 -> n3 -> n4 -> None
            if n==head: # n1
                n.next = None # n1.next = None
            else:
                n.next = head # n2.next = n1 -> n3.next = n2 -> n4.next = n3
                head = n # head = n2 -> n3 -> n4
            n = after # n = n2 -> n3 -> n4 -> None

In [ ]:
#reverse
def reverse(head):
    curr=head
    prev=None
    while curr!=None:
        temp=curr.next
        curr.next=prev
        prev=curr
        curr=temp

In [ ]:
#leftRotate 10 20 30 40 -> 20 30 40 10
def leftRotate(head):
        first_node = head
        head = head.next
        n = head
        while n.next!=None:
            n=n.next
        n.next = first_node
        first_node.next = None

In [ ]:
#right rotate  10 20 30 40 -> 40 10 20 30
def rightRotate(head):
    bckup_head=head
    n=head
    while n!=None:
        n=n.next
    head=n
    head.next=bckup_head.next
    head.next=None

Dummy Headed Doubly Circular Linked List
---

In [ ]:
class DummyLL:
        def __init__(self,elem,next=None,prev=None):
            self.elem = elem
            self.next = next
            self.prev = prev

In [ ]:
#append
def append(data,head):
    node=DummyLL(data)
    lastNode=head.prev
    lastNode.next=node
    node.prev=lastNode
    node.next=head
    head.prev=node


In [ ]:
#insert
def insert(head,data,idx): # 1 2-> 1 3 2
    node=DummyLL(data)
    ins_node=nodeAt(idx)
    prev=ins_node.prev
    prev.next=node
    node.prev=prev
    node.next=ins_node
    ins_node.prev=node

In [ ]:
#remove
def remove(head,idx):
    rmv_node=nodeAt(idx)
    prev=rmv_node.prev
    next=rmv_node.next
    rmv_node.prev=None
    rmv_node.next=None
    prev.next=next
    next.prev=prev

Stack
---

In [ ]:
#ArrayStack
class arrayStack:

    def __init__(self,arr):
        self.arr=arr
        self.size=0
    def push(self,elem):
        if self.size>len(arr):
            return "Overflow"
        else:
            arr[self.size]=elem
            self.size+=1
            return arr
    def pop(self):
        if self.size==0:
            return "Null"
        else:
            arr[self.size-1]=0
            self.size-=1
            return arr
    def peek(self):
        if self.size==0:
            return "Null"
        else:
            return arr[self.size-1]


arr=np.zeros(5,dtype=int)
a=arrayStack(arr)
print(a.push(10))
print(a.peek())
print(a.pop())

[10  0  0  0  0]
10
[0 0 0 0 0]


In [ ]:
class Node:
    def __init__(self,elem,next=None):
        self.elem=elem
        self.next=next


In [ ]:
#LinkedListStack
class ListStack:
    def __init__(self):
        self.newStacktop=None
        self.top=None
    def push(self,elem):
        new=Node(elem)
        if self.top==None:
            self.top=new
        else:
            new.next=self.top
            self.top=new
    def pop(self):
        if self.top==None:
            return "Underflow"
        else:
            bckup=self.top
            self.top=self.top.next
            bckup.next=None
            return bckup.elem
    def peek(self):
        return self.top.elem
    def conditional_reverse(self):
        while self.top!=None:
            if self.newStacktop==None:
                self.newStacktop=Node(self.pop())
            else:
                if self.newStacktop.elem!=self.peek():
                    new=Node(self.pop())
                    new.next=self.newStacktop
                    self.newStacktop=new
                    print(self.newStacktop.elem)
                else:
                    self.top=self.top.next

a=ListStack()
a.push(10)
a.push(10)
a.push(20)
a.push(20)
a.push(30)
a.push(10)
a.push(50)
a.conditional_reverse()

10
30
20
10


In [ ]:
#Infix to postfix
    def reverseStack(self,s):
        string=s
        for i in range(len(string)):
            self.push(string[i])
        rvrs=""
        while self.top!=None:
            rvrs+=self.pop()
        print(rvrs)

    def post_exp(self,st):
        result=0
        for chr in st:
            if "0"<=chr<="9":
                self.push(int(chr))
            else:
                nmb2=self.pop()
                nmb1=self.pop()
                if chr=="+":
                    result=nmb1+nmb2
                elif chr=="-":
                    result=nmb1-nmb2
                elif chr=="*":
                    result=nmb1*nmb2
                elif chr=="/":
                    result=nmb1/nmb2
                self.push(result)
        print(int(result))


In [ ]:

    def inTopo(self,stg):
        s=""
        for chr in stg:
            if chr not in "(){}[]":
                if "0"<=chr<="9":
                    s+=chr
                    print(s)
                else:
                    if self.top==None:
                        self.push(chr)
                        print(chr)
                    elif (self.peek()=="+" or self.peek()=="-") and (chr=="*" or chr=="/" or chr=="%"):
                        self.push(chr)
                        print(chr)
                    else:
                        s+=self.pop()
                        if self.top!=None:
                            if self.peek()=="*" or self.peek()=="+":
                                s+=self.pop()
                                print(s)
                                print(chr)
                        self.push(chr)
        s+=self.top.elem
        print(s)

    def count_diamond(self,stack,s):
        c=0
        for chr in s:
            if chr!=".":
                if chr=="<":
                    self.push(chr)
                elif chr==">":
                    if self.top==None:
                        break
                    else:
                        self.pop()
                        c+=1
        print(c)

In [ ]:
#Parathesis Balancing


In [ ]:
new=[None]*5
print(type(new))

<class 'list'>


In [ ]:
arr=np.array([1,2,3,4,5])
new_arr=arr
print(new_arr[0])

1


In [ ]:
arr=np.array([1,2,3,0,0])
print(arr.size)

5
